### ISSUE TITLE
In group Default and does not have a next rankup - a wrong statement

### ISSUE THREAD

**Issue by WoAnerges** [Armarr/Autorank-2#32]
I do have everything configured for the group "Default" to upgrade to the group "Member" after 2 hours of gameplay, yet still I, as a player in the group "Default" receive the message "... is in group Default and does not have a next rankup"

```
ranks:
    Default:
        requirements:
            time: 2h
#            votes: 11
        results:
            rank change: Default;Member
            command: 'say &p has been playing for two hours in total!;say &p has just become an Member and received 1000 Coins + Wooden Tools as a bonus!;money grant &p 1000;give &p 268 1;give &p 269 1;give &p 270 1;give &p 271 1;give &p 290 1'
            message: '&fCongratulations, you are now Member! You can chat now. &fYou have just received &2&l&o1000 &a&l&oCoins&f and &c&l&oWooden Tools &fas a bonus. You will become an &7VIP &fafter playing for 10 more hours&f.'
            effect: 'ZOMBIE_CHEW_WOODEN_DOOR;8'


```
