### ISSUE TITLE
[question] Whats the differnce between prerequisites and requirements?

### ISSUE THREAD

**Issue by FrozenBeard** [Armarr/Autorank-2#439]
What is the difference between prerequisites and requirements?
I want to have a linear upgrading, where a user goes from rank1 > rank2 > rank3.
Would I need to put their previous rank in the prerequisites? Or use a permission from that rank?

**Comment by Staartvin** [comment]
Please keep an eye on the wiki: I'm currently working on providing proper documentation. 
To provide a short answer: prerequisites are requirements that should be met before a user can choose the path, 'normal' requirements need to be met **after the player has chosen the path** to complete the current path he/she is on.

If you want players to rank up from one path to another, you can put your ranks in the prerequisites, then add requirements for them to complete and finally a rank change result to rank them to a new rank. 

An example:

```YAML
Rank1ToRank2:
    prerequisites:
        in group: 'Rank1'
    requirements:
        money: 5000
        gamemode: 2
        world: world_nether
    results:
        rank change: 'Rank2'
```
