### ISSUE TITLE
Autorank & Privileges, enimies?

### ISSUE THREAD

**Issue by snyper82** [Armarr/Autorank-2#64]
I'm setting up my server (again) to use autorank.  I'm using the simple config so there can't be much wrong there.

```
guest: trusted after 8h
trusted: vip after 8d
```

My privileges groups.yml (minus most permissions):

```
groups:
  guest:
    data:
      promotion: trusted
    rank: 10
    permissions:
    - autorank.check
    inheritance: []
  trusted:
    data:
      demotion: guest
      promotion: vip
    rank: 30
    permissions:
    - autorank.leaderboard
    inheritance:
    - guest
  vip:
    data:
      demotion: trusted
    rank: 50
    permissions:
    inheritance:
    - trusted 
  mod:
    rank: 100
    permissions:
    - autorank.checkothers
    - autorank.add
    - autorank.set
    - autorank.set.others
    - autorank.remove
    - autorank.debug
    - autorank.reload
    inheritance:
    - vip
    data:
      promotion: admin
  admin:
    rank: 300
    permissions:
    - autorank.sync
    - autorank.warning.notice
    inheritance:
    - mod
    data:
      demotion: mod
```

Now the issues

First as admin /ar check demotes... not good
Second, even though I can place myself in guest (via console) then /ar check which promotes on-screen but doesn't actually promote.
